FROM scratch
WORKDIR /etc/ssl/certs
COPY --chmod=0644 deploy/docker/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chown=10001:10001 deploy/docker/jingshield-linux-amd64 /usr/local/bin/jingshield
WORKDIR /etc/jingshield
COPY --chmod=0644 deploy/docker/config.yaml /etc/jingshield/config.yaml
WORKDIR /var/lib/jingshield
USER 10001:10001
EXPOSE 18080
ENTRYPOINT ["/usr/local/bin/jingshield", "serve", "-c", "/etc/jingshield/config.yaml"]
